name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup terraform CLI
      uses: hashicorp/setup-terraform@v3

    - name: terraform fmt
      run: terraform fmt -check

    - name: terraform init
      run: terraform init

    - name: terraform validate
      run: terraform validate -no-color